name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./regressions/

    steps:
    - uses: actions/checkout@v1
    - name: Set execute flags for regression tests
      run: chmod +x ./regression_test*.sh      
    - name: Run regression_test1.sh
      run: bash ./run_regression_tests.sh
